"""
Logistic Regression baseline model for the WorldCup Intelligence Platform.

This module trains a multinomial Logistic Regression model using the
ML-ready dataset generated by the feature engineering pipeline.

The workflow is:

Load Dataset
    ↓
Select Features
    ↓
Chronological Train/Test Split
    ↓
Standard Scaling
    ↓
Train Logistic Regression
    ↓
Predict Probabilities
    ↓
Evaluate
    ↓
Save Model
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import joblib
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    log_loss,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

PROJECT_ROOT = Path(__file__).resolve().parents[3]

DATA_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "ml_matches.csv"
)

MODEL_PATH = (
    PROJECT_ROOT
    / "models"
    / "logistic_regression.joblib"
)


FEATURE_COLUMNS = [

    "home_elo",
    "away_elo",
    "elo_diff",

    "home_expected_elo",
    "away_expected_elo",

    "neutral",
    "home_advantage_applied",

    "tournament_k_factor",

    "home_matches_played",
    "away_matches_played",
    "matches_played_diff",

    "home_recent_points_per_match",
    "away_recent_points_per_match",
    "recent_points_diff",

    "home_recent_goals_for",
    "away_recent_goals_for",
    "recent_goals_for_diff",

    "home_recent_goals_against",
    "away_recent_goals_against",
    "recent_goals_against_diff",

    "home_recent_goal_difference",
    "away_recent_goal_difference",
    "recent_goal_difference_diff",

    "home_rest_days",
    "away_rest_days",
    "rest_days_diff",

    "head_to_head_matches",

    "home_head_to_head_points_per_match",
    "away_head_to_head_points_per_match",
    "head_to_head_points_diff",
]


TARGET_COLUMN = "target_code"


@dataclass
class DatasetSplit:

    X_train: pd.DataFrame
    X_test: pd.DataFrame

    y_train: pd.Series
    y_test: pd.Series


@dataclass
class EvaluationResult:

    accuracy: float

    log_loss: float

    confusion_matrix: Any

    classification_report: dict[str, Any]


class LogisticMatchPredictor:

    def __init__(
        self,
        random_state: int = 42,
        test_size: float = 0.20,
    ) -> None:

        self.random_state = random_state

        self.test_size = test_size

        self.pipeline = Pipeline(
            [
                (
                    "scaler",
                    StandardScaler(),
                ),
                (
                    "classifier",
                    LogisticRegression(
                        multi_class="multinomial",
                        solver="lbfgs",
                        max_iter=1000,
                        random_state=random_state,
                    ),
                ),
            ]
        )

        self.is_trained = False

    @staticmethod
    def load_dataset(
        dataset_path: Path | str = DATA_PATH,
    ) -> pd.DataFrame:

        dataframe = pd.read_csv(dataset_path)

        dataframe = dataframe.sort_values(
            "match_index"
        ).reset_index(drop=True)

        return dataframe

    @staticmethod
    def prepare_features(
        dataframe: pd.DataFrame,
    ) -> tuple[pd.DataFrame, pd.Series]:

        X = dataframe[FEATURE_COLUMNS].copy()

        y = dataframe[TARGET_COLUMN].copy()

        return X, y

    def chronological_split(
        self,
        dataframe: pd.DataFrame,
    ) -> DatasetSplit:

        split_index = int(
            len(dataframe)
            * (1 - self.test_size)
        )

        train = dataframe.iloc[:split_index]

        test = dataframe.iloc[split_index:]

        X_train = train[FEATURE_COLUMNS]

        X_test = test[FEATURE_COLUMNS]

        y_train = train[TARGET_COLUMN]

        y_test = test[TARGET_COLUMN]

        return DatasetSplit(
            X_train=X_train,
            X_test=X_test,
            y_train=y_train,
            y_test=y_test,
        )
    
        def train(
        self,
        dataframe: pd.DataFrame,
    ) -> None:

        dataset = self.chronological_split(dataframe)

        self.pipeline.fit(
            dataset.X_train,
            dataset.y_train,
        )

        self.is_trained = True

    def predict(
        self,
        features: pd.DataFrame,
    ) -> Any:

        if not self.is_trained:
            raise RuntimeError(
                "Model has not been trained."
            )

        return self.pipeline.predict(features)

    def predict_proba(
        self,
        features: pd.DataFrame,
    ) -> Any:

        if not self.is_trained:
            raise RuntimeError(
                "Model has not been trained."
            )

        return self.pipeline.predict_proba(features)

    def evaluate(
        self,
        dataframe: pd.DataFrame,
    ) -> EvaluationResult:

        if not self.is_trained:
            raise RuntimeError(
                "Model has not been trained."
            )

        dataset = self.chronological_split(dataframe)

        predictions = self.pipeline.predict(
            dataset.X_test
        )

        probabilities = self.pipeline.predict_proba(
            dataset.X_test
        )

        accuracy = accuracy_score(
            dataset.y_test,
            predictions,
        )

        loss = log_loss(
            dataset.y_test,
            probabilities,
        )

        matrix = confusion_matrix(
            dataset.y_test,
            predictions,
        )

        report = classification_report(
            dataset.y_test,
            predictions,
            output_dict=True,
        )

        return EvaluationResult(
            accuracy=accuracy,
            log_loss=loss,
            confusion_matrix=matrix,
            classification_report=report,
        )

    def train_and_evaluate(
        self,
        dataset_path: Path | str = DATA_PATH,
    ) -> EvaluationResult:

        dataframe = self.load_dataset(
            dataset_path
        )

        self.train(dataframe)

        return self.evaluate(dataframe)

    def save_model(
        self,
        output_path: Path | str = MODEL_PATH,
    ) -> None:

        output_path = Path(output_path)

        output_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        joblib.dump(
            self.pipeline,
            output_path,
        )

    def load_model(
        self,
        model_path: Path | str = MODEL_PATH,
    ) -> None:

        self.pipeline = joblib.load(
            model_path
        )

        self.is_trained = True

    @property
    def coefficients(self) -> pd.DataFrame:

        if not self.is_trained:
            raise RuntimeError(
                "Model has not been trained."
            )

        classifier = self.pipeline.named_steps[
            "classifier"
        ]

        return pd.DataFrame(
            classifier.coef_,
            columns=FEATURE_COLUMNS,
        )

    @property
    def intercept(self) -> Any:

        if not self.is_trained:
            raise RuntimeError(
                "Model has not been trained."
            )

        classifier = self.pipeline.named_steps[
            "classifier"
        ]

        return classifier.intercept_
    
    